AWSTemplateFormatVersion: 2010-09-09
Description: Create Security Group and Instance Profile

Resources:

  EC2InstanceS3AccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      Description: Role to provide access to S3 created by Cloudformation
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - "s3:PutOjbect"
                  - "s3:Get*"
                  - "s3:List"
                Resource: "*"
          PolicyName: OssEC2S3Access
      RoleName: cf-OssEC2S3AccessRole

  EC2InstanceProfileS3:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: EC2InstanceProfileS3
      Roles: 
        - !Ref EC2InstanceS3AccessRole


Outputs:
  EC2InstanceProfileS3:
    Value: !Ref EC2InstanceProfileS3
    Export:
      Name: EC2InstanceProfileS3




            
      

