AWSTemplateFormatVersion: 2010-09-09
Parameters:

# Imports
  vpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-08e429b53dcd87621
  
  # qb-subnet-private1-ap-northeast-2a
  SubnetA:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for tomcat 
    Default: subnet-0d27f71424c62a78e

  MyKeyPair:
    Description: 'use for EC2 instance' 
    Type: AWS::EC2::KeyPair::KeyName
    Default: aws-ec2

  WasSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for tomcat
    Default: sg-049e4d876729a83c1

  InstanceProfileName:
    Description: EC2 instance Porilfe access to S3
    Type: String
    Default: EC2InstanceProfileS3 

  BucketName:
    Type: String
    Default: steve-codedeploy-bucket

  AMI:
    Description: 'AMI of EC2'
    Type: AWS::EC2::Image::Id
    Default: ami-0fd0765afb77bcca7

  Env:
    Description: 'dev, prod'
    Type: String
    Default: 'dev'

Resources:

# Launch template for the tomcat app servers & supporting config files
  QuaterbackLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: 'cf-Launch-Template-Tomcat9'
      LaunchTemplateData:
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            DeleteOnTermination: true
            SubnetId: !Ref SubnetA
            # Security Group Id
            Groups: [!Ref WasSecurityGroup]
        ImageId: !Ref AMI
        # Instance Profile Name
        IamInstanceProfile: 
          Arn: !Sub arn:aws:iam::${AWS::AccountId}:instance-profile/${InstanceProfileName}
        InstanceType: t3.medium
        KeyName: !Ref MyKeyPair
        
        TagSpecifications:
        - ResourceType: instance
          Tags:
          - Key: Name
            Value: quarterback tomcat
        UserData: 
          Fn::Base64: !Sub |
            #!/bin/bash
            sudo yum update -y
            cd /home/ec2-user

            # modify kuernel setting
            aws s3api get-object s3://${BucketName}/${Env}/lib/config/qb/sysctl.conf sysctl.conf
            cp sysctl.conf /etc/sysctl.conf
            sysctl -p

            # install jdk 15
            sudo rpm --import https://yum.corretto.aws/corretto.key 
            sudo curl -L -o /etc/yum.repos.d/corretto.repo https://yum.corretto.aws/corretto.repo
            sudo yum install -y java-15-amazon-corretto-devel
            sudo aws s3api get-object --bucket ${BucketName} --key ${Env}/config/qb/tomcat.service /etc/systemd/system/tomcat.service
            useradd -d /opt/tomcat -s /bin/nologin tomcat
            
            # tommcat install
            sudo aws s3api get-object --bucket ${BucketName} --key ${Env}/lib/qb/apache-tomcat-9.0.64.tar.gz /tmp/apache-tomcat-9.0.64.tar.gz
            tar -zxvf /tmp/apache-tomcat-*.tar.gz
            mkdir -p /opt/tomcat
            mv apache-tomcat-9.0.64/* /opt/tomcat
            
            chown -R tomcat:tomcat /opt/tomcat
            sudo systemctl daemon-reload
            sudo systemctl start tomcat
            sudo systemctl enable tomcat
            cd /home/ec2-user
            sudo aws s3api get-object --bucket ${BucketName} --key ${Env}/lib/qb/mysql-connector-java-8.0.29.jar /opt/tomcat/lib/mysql-connector-java-8.0.29.jar
            sudo aws s3api get-object --bucket ${BucketName} --key ${Env}/config/qb/server.xml /opt/tomcat/conf/server.xml
            sudo aws s3api get-object --bucket ${BucketName} --key ${Env}/config/qb/context.xml /opt/tomcat/conf/context.xml
            sudo chown tomcat:tomcat /opt/tomcat/lib/mysql-connector-java-8.0.29.jar
            sudo systemctl restart tomcat
  # TomcatInstance:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     LaunchTemplate:
  #       LaunchTemplateId: !Ref QuaterbackLaunchTemplate
  #       Version: !GetAtt QuaterbackLaunchTemplate.LatestVersionNumber





