AWSTemplateFormatVersion: 2010-09-09
Parameters:
  vpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-435bcc28
  
  # ap-northeast-2a
  SubnetA:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for tomcat 
    Default: subnet-a720a1cc

  myKeyPair:
    Description: 'use for EC2 instance' 
    Type: AWS::EC2::KeyPair::KeyName
    Default: aws-ec2

Resources:
  
  CodeDeployInstancePermission:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      Description: Role to provide access to S3
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - "s3:PubOjbect"
                  - "s3:Get*"
                  - "s3:List"
                Resource: "*"
          PolicyName: CodeDeployS3Access
      RoleName: CodeDeployS3AccessRole





            
      

