version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deployed

hooks:
  AfterInstall:
    - location: scripts/application_deploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/delete_artifacts.sh
      timeout: 300
      runas: root
    
  