version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deployed/TestApp

hooks:
  AfterInstall:
    - location: scripts/application_deploy.sh
      timeout: 300
      runas: root
  